version: '3.8'

services:
  keycloak:
    image: keycloak/keycloak:24.0
    container_name: keycloak
    environment:
      - DB_VENDOR=mysql
      - DB_ADDR=mysql
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=keycloak
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    volumes:
      - /home/ubuntu/docker/keycloak/conf:/opt/keycloak/conf # Mount as a directory
      - /home/ubuntu/docker/keycloak/providers:/opt/keycloak/providers   
      - /home/ubuntu/docker/keycloak/entryscripts/server.sh:/opt/keycloak/entryscripts/server.sh
    entrypoint: ["/opt/keycloak/entryscripts/server.sh"]  
    #entrypoint: ["/opt/keycloak/bin/kc.sh", "start-dev"]
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.20
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=keycloak
      - MYSQL_USER=keycloak
      - MYSQL_PASSWORD=keycloak
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - keycloak

volumes:
  mysql_data:

