services:
  keycloak:
    image: keycloak/keycloak:24.0
    container_name: keycloak
    ports:
      - "8080:8080"
      - "8443:8443"  # Ensure HTTPS port is mapped
    volumes:
      - /home/ubuntu/keycloak/conf:/opt/keycloak/conf
      - /home/ubuntu/keycloak/ssl:/etc/keycloak/ssl
      - /home/ubuntu/keycloak/providers:/opt/keycloak/providers  
      #- /home/ubuntu/keycloak/themes:/opt/keycloak/themes
      - /home/ubuntu/keycloak/scripts:/opt/keycloak/scripts  
    entrypoint: ["/opt/keycloak/scripts/server.sh"]
    depends_on:
      - mysql
    environment:
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=keycloak    
        #- KEYCLOAK_ADMIN=admin   
        #- KEYCLOAK_ADMIN_PASSWORD=admin 
    restart: always

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=<your-db-password>
      - MYSQL_DATABASE=keycloak
      - MYSQL_USER=keycloak
      - MYSQL_PASSWORD=keycloak
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

        
  nginx:
    image: nginx:alpine3.20-perl
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - keycloak
    restart: always

volumes:
  mysql_data:
